board_config = 
  [[0, 0, white_rook],
   [1, 0, white_knight],
   [2, 0, white_bishop],
   [3, 0, white_queen],
   [4, 0, white_king],
   [5, 0, white_bishop],
   [6, 0, white_knight],
   [7, 0, white_rook],
   [0, 1, white_pawn],
   [1, 1, white_pawn],
   [2, 1, white_pawn],
   [3, 1, white_pawn],
   [4, 1, white_pawn],
   [5, 1, white_pawn],
   [6, 1, white_pawn],
   [7, 1, white_pawn],
   [0, 2],
   [1, 2],
   [2, 2],
   [3, 2],
   [4, 2],
   [5, 2],
   [6, 2],
   [7, 2]]